package com.running4light.gdms.pojo;

import java.io.Serializable;
import java.util.Date;

public class Docs implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docs.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docs.UID
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docs.DOC_NAME
     *
     * @mbggenerated
     */
    private String docName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docs.DOC_URL
     *
     * @mbggenerated
     */
    private String docUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docs.CLASSIFY
     *
     * @mbggenerated
     */
    private String classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docs.DOC_TYPE
     *
     * @mbggenerated
     */
    private String docType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docs.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table docs
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docs.ID
     *
     * @return the value of docs.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docs.ID
     *
     * @param id the value for docs.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docs.UID
     *
     * @return the value of docs.UID
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docs.UID
     *
     * @param uid the value for docs.UID
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docs.DOC_NAME
     *
     * @return the value of docs.DOC_NAME
     *
     * @mbggenerated
     */
    public String getDocName() {
        return docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docs.DOC_NAME
     *
     * @param docName the value for docs.DOC_NAME
     *
     * @mbggenerated
     */
    public void setDocName(String docName) {
        this.docName = docName == null ? null : docName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docs.DOC_URL
     *
     * @return the value of docs.DOC_URL
     *
     * @mbggenerated
     */
    public String getDocUrl() {
        return docUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docs.DOC_URL
     *
     * @param docUrl the value for docs.DOC_URL
     *
     * @mbggenerated
     */
    public void setDocUrl(String docUrl) {
        this.docUrl = docUrl == null ? null : docUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docs.CLASSIFY
     *
     * @return the value of docs.CLASSIFY
     *
     * @mbggenerated
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docs.CLASSIFY
     *
     * @param classify the value for docs.CLASSIFY
     *
     * @mbggenerated
     */
    public void setClassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docs.DOC_TYPE
     *
     * @return the value of docs.DOC_TYPE
     *
     * @mbggenerated
     */
    public String getDocType() {
        return docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docs.DOC_TYPE
     *
     * @param docType the value for docs.DOC_TYPE
     *
     * @mbggenerated
     */
    public void setDocType(String docType) {
        this.docType = docType == null ? null : docType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docs.CREATE_TIME
     *
     * @return the value of docs.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docs.CREATE_TIME
     *
     * @param createTime the value for docs.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table docs
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", docName=").append(docName);
        sb.append(", docUrl=").append(docUrl);
        sb.append(", classify=").append(classify);
        sb.append(", docType=").append(docType);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}