package com.running4light.gdms.pojo;

import java.io.Serializable;

public class Proccess implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.ID
     *
     * @mbggenerated
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.S_ID
     *
     * @mbggenerated
     */
    private String sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process
     *
     * @mbggenerated
     */
    private Float process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.st
     *
     * @mbggenerated
     */
    private Float st;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.need
     *
     * @mbggenerated
     */
    private Float need;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.sysdesign
     *
     * @mbggenerated
     */
    private Float sysdesign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.test
     *
     * @mbggenerated
     */
    private Float test;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.report
     *
     * @mbggenerated
     */
    private Float report;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.paper
     *
     * @mbggenerated
     */
    private Float paper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table process
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.ID
     *
     * @return the value of process.ID
     *
     * @mbggenerated
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.ID
     *
     * @param id the value for process.ID
     *
     * @mbggenerated
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.S_ID
     *
     * @return the value of process.S_ID
     *
     * @mbggenerated
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.S_ID
     *
     * @param sId the value for process.S_ID
     *
     * @mbggenerated
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process
     *
     * @return the value of process.process
     *
     * @mbggenerated
     */
    public Float getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process
     *
     * @param process the value for process.process
     *
     * @mbggenerated
     */
    public void setProcess(Float process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.st
     *
     * @return the value of process.st
     *
     * @mbggenerated
     */
    public Float getSt() {
        return st;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.st
     *
     * @param st the value for process.st
     *
     * @mbggenerated
     */
    public void setSt(Float st) {
        this.st = st;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.need
     *
     * @return the value of process.need
     *
     * @mbggenerated
     */
    public Float getNeed() {
        return need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.need
     *
     * @param need the value for process.need
     *
     * @mbggenerated
     */
    public void setNeed(Float need) {
        this.need = need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.sysdesign
     *
     * @return the value of process.sysdesign
     *
     * @mbggenerated
     */
    public Float getSysdesign() {
        return sysdesign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.sysdesign
     *
     * @param sysdesign the value for process.sysdesign
     *
     * @mbggenerated
     */
    public void setSysdesign(Float sysdesign) {
        this.sysdesign = sysdesign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.test
     *
     * @return the value of process.test
     *
     * @mbggenerated
     */
    public Float getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.test
     *
     * @param test the value for process.test
     *
     * @mbggenerated
     */
    public void setTest(Float test) {
        this.test = test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.report
     *
     * @return the value of process.report
     *
     * @mbggenerated
     */
    public Float getReport() {
        return report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.report
     *
     * @param report the value for process.report
     *
     * @mbggenerated
     */
    public void setReport(Float report) {
        this.report = report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.paper
     *
     * @return the value of process.paper
     *
     * @mbggenerated
     */
    public Float getPaper() {
        return paper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.paper
     *
     * @param paper the value for process.paper
     *
     * @mbggenerated
     */
    public void setPaper(Float paper) {
        this.paper = paper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sId=").append(sId);
        sb.append(", process=").append(process);
        sb.append(", st=").append(st);
        sb.append(", need=").append(need);
        sb.append(", sysdesign=").append(sysdesign);
        sb.append(", test=").append(test);
        sb.append(", report=").append(report);
        sb.append(", paper=").append(paper);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}