package com.running4light.gdms.pojo;

import java.io.Serializable;

public class Searchs implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchs.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchs.key_name
     *
     * @mbggenerated
     */
    private String keyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchs.weight
     *
     * @mbggenerated
     */
    private Byte weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchs.times
     *
     * @mbggenerated
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table searchs
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchs.ID
     *
     * @return the value of searchs.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchs.ID
     *
     * @param id the value for searchs.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchs.key_name
     *
     * @return the value of searchs.key_name
     *
     * @mbggenerated
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchs.key_name
     *
     * @param keyName the value for searchs.key_name
     *
     * @mbggenerated
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchs.weight
     *
     * @return the value of searchs.weight
     *
     * @mbggenerated
     */
    public Byte getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchs.weight
     *
     * @param weight the value for searchs.weight
     *
     * @mbggenerated
     */
    public void setWeight(Byte weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchs.times
     *
     * @return the value of searchs.times
     *
     * @mbggenerated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchs.times
     *
     * @param times the value for searchs.times
     *
     * @mbggenerated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchs
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", keyName=").append(keyName);
        sb.append(", weight=").append(weight);
        sb.append(", times=").append(times);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}