package com.running4light.gdms.pojo;
import java.io.Serializable;

public class St implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st.ID
     *
     * @mbggenerated
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st.TOPIC_ID
     *
     * @mbggenerated
     */
    private String topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st.TOPIC_NAME
     *
     * @mbggenerated
     */
    private String topicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st.S_ID
     *
     * @mbggenerated
     */
    private String sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st.STUDENT_NAME
     *
     * @mbggenerated
     */
    private String studentName;
    
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table st
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

//	public St(String topicId, String topicName, String sId, String studentName) {
//		this.topicId = topicId;
//		this.topicName = topicName;
//		this.sId = sId;
//		this.studentName = studentName;
//	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st.ID
     *
     * @return the value of st.ID
     *
     * @mbggenerated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st.ID
     *
     * @param id the value for st.ID
     *
     * @mbggenerated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st.TOPIC_ID
     *
     * @return the value of st.TOPIC_ID
     *
     * @mbggenerated
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st.TOPIC_ID
     *
     * @param topicId the value for st.TOPIC_ID
     *
     * @mbggenerated
     */
    public void setTopicId(String topicId) {
        this.topicId = topicId == null ? null : topicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st.TOPIC_NAME
     *
     * @return the value of st.TOPIC_NAME
     *
     * @mbggenerated
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st.TOPIC_NAME
     *
     * @param topicName the value for st.TOPIC_NAME
     *
     * @mbggenerated
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st.S_ID
     *
     * @return the value of st.S_ID
     *
     * @mbggenerated
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st.S_ID
     *
     * @param sId the value for st.S_ID
     *
     * @mbggenerated
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st.STUDENT_NAME
     *
     * @return the value of st.STUDENT_NAME
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st.STUDENT_NAME
     *
     * @param studentName the value for st.STUDENT_NAME
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    
    public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st
     *
     * @mbggenerated
     */
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", topicId=").append(topicId);
        sb.append(", topicName=").append(topicName);
        sb.append(", sId=").append(sId);
        sb.append(", studentName=").append(studentName);
        sb.append(", teacherName=").append(teacherName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}