package com.running4light.gdms.pojo;

import java.io.Serializable;

public class States implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.STATENAME
     *
     * @mbggenerated
     */
    private String statename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table states
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.ID
     *
     * @return the value of states.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.ID
     *
     * @param id the value for states.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.STATENAME
     *
     * @return the value of states.STATENAME
     *
     * @mbggenerated
     */
    public String getStatename() {
        return statename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.STATENAME
     *
     * @param statename the value for states.STATENAME
     *
     * @mbggenerated
     */
    public void setStatename(String statename) {
        this.statename = statename == null ? null : statename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.STATE
     *
     * @return the value of states.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.STATE
     *
     * @param state the value for states.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table states
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", statename=").append(statename);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}