package com.running4light.gdms.pojo;
import java.io.Serializable;

public class Teacher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.ID
     *
     * @mbggenerated
     */
	private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.DEPT_ID
     *
     * @mbggenerated
     */
    private Byte deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.IDENTITY
     *
     * @mbggenerated
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.TEL
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.RANK
     *
     * @mbggenerated
     */
    private String rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.ID
     *
     * @return the value of teacher.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.ID
     *
     * @param id the value for teacher.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.USERNAME
     *
     * @return the value of teacher.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.USERNAME
     *
     * @param username the value for teacher.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.PASSWORD
     *
     * @return the value of teacher.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.PASSWORD
     *
     * @param password the value for teacher.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.DEPT_ID
     *
     * @return the value of teacher.DEPT_ID
     *
     * @mbggenerated
     */
    public Byte getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.DEPT_ID
     *
     * @param deptId the value for teacher.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(Byte deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.IDENTITY
     *
     * @return the value of teacher.IDENTITY
     *
     * @mbggenerated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.IDENTITY
     *
     * @param identity the value for teacher.IDENTITY
     *
     * @mbggenerated
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.SEX
     *
     * @return the value of teacher.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.SEX
     *
     * @param sex the value for teacher.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.TEL
     *
     * @return the value of teacher.TEL
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.TEL
     *
     * @param tel the value for teacher.TEL
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.RANK
     *
     * @return the value of teacher.RANK
     *
     * @mbggenerated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.RANK
     *
     * @param rank the value for teacher.RANK
     *
     * @mbggenerated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.EMAIL
     *
     * @return the value of teacher.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.EMAIL
     *
     * @param email the value for teacher.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", deptId=").append(deptId);
        sb.append(", identity=").append(identity);
        sb.append(", sex=").append(sex);
        sb.append(", tel=").append(tel);
        sb.append(", rank=").append(rank);
        sb.append(", email=").append(email);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}