package com.running4light.gdms.pojo;
import java.io.Serializable;
import java.util.Date;

public class Topic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.TOPIC_NAME
     *
     * @mbggenerated
     */
    private String topicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.TEACHER_NAME
     *
     * @mbggenerated
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.DEMAND
     *
     * @mbggenerated
     */
    private String demand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.TOPIC_TYPE
     *
     * @mbggenerated
     */
    private String topicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.TAG
     *
     * @mbggenerated
     */
    private Integer tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.UPLOAD_TIME
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.ID
     *
     * @return the value of topic.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.ID
     *
     * @param id the value for topic.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.TOPIC_NAME
     *
     * @return the value of topic.TOPIC_NAME
     *
     * @mbggenerated
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.TOPIC_NAME
     *
     * @param topicName the value for topic.TOPIC_NAME
     *
     * @mbggenerated
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.TEACHER_NAME
     *
     * @return the value of topic.TEACHER_NAME
     *
     * @mbggenerated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.TEACHER_NAME
     *
     * @param teacherName the value for topic.TEACHER_NAME
     *
     * @mbggenerated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.CONTENT
     *
     * @return the value of topic.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.CONTENT
     *
     * @param content the value for topic.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.DEMAND
     *
     * @return the value of topic.DEMAND
     *
     * @mbggenerated
     */
    public String getDemand() {
        return demand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.DEMAND
     *
     * @param demand the value for topic.DEMAND
     *
     * @mbggenerated
     */
    public void setDemand(String demand) {
        this.demand = demand == null ? null : demand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.TOPIC_TYPE
     *
     * @return the value of topic.TOPIC_TYPE
     *
     * @mbggenerated
     */
    public String getTopicType() {
        return topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.TOPIC_TYPE
     *
     * @param topicType the value for topic.TOPIC_TYPE
     *
     * @mbggenerated
     */
    public void setTopicType(String topicType) {
        this.topicType = topicType == null ? null : topicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.STATE
     *
     * @return the value of topic.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.STATE
     *
     * @param state the value for topic.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.TAG
     *
     * @return the value of topic.TAG
     *
     * @mbggenerated
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.TAG
     *
     * @param tag the value for topic.TAG
     *
     * @mbggenerated
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.UPLOAD_TIME
     *
     * @return the value of topic.UPLOAD_TIME
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.UPLOAD_TIME
     *
     * @param uploadTime the value for topic.UPLOAD_TIME
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", topicName=").append(topicName);
        sb.append(", teacherName=").append(teacherName);
        sb.append(", content=").append(content);
        sb.append(", demand=").append(demand);
        sb.append(", topicType=").append(topicType);
        sb.append(", state=").append(state);
        sb.append(", tag=").append(tag);
        sb.append(", uploadTime=").append(uploadTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}