package com.running4light.gdms.dao;

import java.util.List;

import com.running4light.gdms.pojo.Fileclassify;

public interface FileclassifyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileclassify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileclassify
     *
     * @mbggenerated
     */
    int insert(Fileclassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileclassify
     *
     * @mbggenerated
     */
    Fileclassify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileclassify
     *
     * @mbggenerated
     */
    List<Fileclassify> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileclassify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fileclassify record);
}