package com.running4light.gdms.dao;

import com.running4light.gdms.pojo.Findpswinfos;
import java.util.List;

public interface FindpswinfosDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table findpswinfos
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table findpswinfos
     *
     * @mbggenerated
     */
    int insert(Findpswinfos findpswinfos);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table findpswinfos
     *
     * @mbggenerated
     */
    Findpswinfos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table findpswinfos
     *
     * @mbggenerated
     */
    List<Findpswinfos> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table findpswinfos
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Findpswinfos findpswinfos);

	Findpswinfos selectByUid(String uid);
}