package com.running4light.gdms.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.running4light.gdms.pojo.Mubanfiles;

public interface MubanfilesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mubanfiles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mubanfiles
     *
     * @mbggenerated
     */
    int insert(Mubanfiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mubanfiles
     *
     * @mbggenerated
     */
    Mubanfiles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mubanfiles
     *
     * @mbggenerated
     */
    List<Mubanfiles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mubanfiles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mubanfiles record);

	List<Mubanfiles> selectPage(Map<String, Object> param);

	Integer countSelectAll(Map<String, Object> param);
	
	int deleteByids(@Param("ids") List<Integer> list);
	
	List<Mubanfiles> selectByids(@Param("ids") List<Integer> list);
}