package com.running4light.gdms.dao;

import com.running4light.gdms.pojo.UserNoticeState;
import java.util.List;

public interface UserNoticeStateDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernoticestate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernoticestate
     *
     * @mbggenerated
     */
    int insert(UserNoticeState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernoticestate
     *
     * @mbggenerated
     */
    UserNoticeState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernoticestate
     *
     * @mbggenerated
     */
    List<UserNoticeState> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usernoticestate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserNoticeState record);
}